---
triggers:
  - conditions:
      gh_event: push
    stages:
      - test

stages:
  test:
    steps:
      - test

jobs:
  test:
    script_name: test
    pre_steps:
      - checkout

scripts:
  checkout:
    run: 'pwd && echo git clone'
    image: docker.io/library/github/sh:master
    command: ['/bin/sh', '-c']
  test:
    run: echo go test -v ./...
    image: docker.io/library/golang:1.26.0-alpine
    command: ['/bin/sh', '-c']
