---
use_templates:
  - Charles546/honeydipper-client@refs/heads/test:hdci.tmpl.yml

cache:
  /local/cached: 'hd-cache-{{ .ctx.git_repo }}-{{ .ctx.git_ref }}'


triggers:
  - conditions:
      gh_event: push
    stages:
      - test
      - check-license

stages:
  check-license:
    jobs:
      - job_name: check-license
        steps:
          - image: docker.io/library/golang:1.26.0-alpine
            executor: sh-c
            run: sleep 10 && echo sleeped and done && ls -l /local/cached
            cache:
              - /local/cached
  test:
    jobs:
      - test
    requires:
      - check-license

jobs:
  test:
    steps:
      - load_secret_driver
      - github_checkout
      - container_name: test
        executor:
          - sh-c
          - run_in_repo
        run: ls -l && date > /local/cached/current_time
        image: docker.io/library/golang:1.26.0-alpine
    cache:
      - /local/cached
